### ISSUE TITLE
Feature Request: Daily Resource Links on Website

### ISSUE THREAD

**Issue by harshithsaiv** [studymlwithme/ML-Resources#1]
I've been following your Instagram videos and find them incredibly helpful. I wanted to suggest an enhancement for the resources website that could benefit a wider audience. It would be very convenient if the daily resources shared in the Instagram videos could also be posted directly on the resources website. This would make it easier for users to access these resources directly from the website rather than having to go through each video.

This could potentially increase user engagement with the website and provide a centralized hub for all resources, making it more streamlined for users to find what they need.

**Comment by studymlwithme** [comment]
Thanks for the FR! I completely agree. I have very limited time, so I am currently working on creating efficiencies that allow me to consistently provide access to resources. I will heavily consider this! :)

**Comment by harshithsaiv** [comment]
I want to  help you with updating the github page website everyday once you push the resources of that particular day into github.
